feat: 2024-12-13 13:55 - Update API specification
devopness/devopness pull request #1087
Opened 2024-12-13 13:55 UTC by devopness-automations

This PR is auto generated to update `spec.json` file.

2024-12-13 20:24 UTC, souz4-my submitted a review, later dismissed

2024-12-15 11:11 UTC, jfoliveira requested changes

2024-12-15 11:11 UTC, jfoliveira commented on .changeset/add-server-rotate-key-operation.md
> +- Add operation server:rotote-key
```suggestion
- Add operation server:rotate-key
```

2024-12-15 11:11 UTC, jfoliveira commented on .changeset/add-description-field-in-action-target.md
> +- Added description field in `ActionStep`
```suggestion
- Added `description` field to `ActionStep` model, so users can understand what's the purpose of a custom pipeline step created by a team member
```

2024-12-16 13:45 UTC, Diegiwg approved these changes

2024-12-16 14:19 UTC, jfoliveira approved these changes

2024-12-16 14:19 UTC, merged