feat: add more instructions of use in README.md
devopness/devopness pull request #643
Opened 2023-02-23 22:45 UTC by souz4-my

Add instructions on how we can contribute to the project correctly so as not to break patterns and layout

2023-02-24 01:11 UTC, jfoliveira requested changes

2023-02-24 01:11 UTC, jfoliveira commented on docs/README.md
> +* `intro`: is description of page but is not required
```suggestion
## Predefined variables
Here is a list of predefined variables that can be set in the `front-matter` block of a documentation topic:

| Variable | Description                               | Required       |
|----------|-------------------------------------------|----------------|
| `title`  | The title of the documentation topic      | Yes            |
| `intro`  | A short paragraph introducing the topic   | No             |
```

2023-02-24 01:31 UTC, souz4-my commented on docs/README.md
> +* `intro`: is description of page but is not required
Aplicado manualmente pois precisava alterar o link para referencia continua funcionando

2023-03-08 11:00 UTC, jfoliveira approved these changes

2023-03-08 11:04 UTC, merged