docs: add note about required permissions on "Add an SSH key" post
devopness/devopness pull request #718
Opened 2023-07-11 04:11 UTC by thlmenezes

## Description of change

Add a note describing to the user the required permissions needed to follow the post successfully

## Issues resolved by this PR

- [x] [DVN-11397]

## More info

Note preview*
![image](https://github.com/devopness/devopness/assets/33532177/1c5dfd5b-6e98-4956-8733-5899a7a660df)

*manually edited the CSS to make the table look prettier, see changes added in the code block below
```css
table {
  @apply my-2;
}

th,td {
  @apply pl-2 pr-2;
}

th:first-child,
td:first-child {
  @apply pl-0;
}

th:last-child,
td:last-child {
  @apply pr-0;
}
```

2023-07-11 19:55 UTC, luizvi approved these changes

2023-07-14 00:11 UTC, jfoliveira requested changes

2023-07-17 04:59 UTC, thlmenezes commented on docs/ssh-keys/add-ssh-key.md
> +| Resource | Permissions |
@jfoliveira updated content structure, now the table will be rendered outside markdown

2023-07-18 23:02 UTC, jfoliveira approved these changes

2023-07-19 02:01 UTC, merged