docs: update webhook related instructions
devopness/devopness pull request #769
Opened 2023-10-16 13:21 UTC by thlmenezes

## Description of change

Update webhook related posts to use new API endpoint

## Issues resolved by this PR

- [x] [DVN-11551]

## More info

2023-10-16 13:22 UTC, thlmenezes commented
Deployed pipeline for `PR #769 (docs: update webhook related instructions)`: Devopness application `thlmenezes-site.devopness.com` deployment **in-progress** on action <https://thlmenezes-site.devopness.com>

2023-10-16 13:24 UTC, thlmenezes commented
Deployed pipeline for `PR #769 (docs: update webhook related instructions)`: Devopness application `thlmenezes-site.devopness.com` deployment **completed** on action <https://thlmenezes-site.devopness.com>

2023-10-16 13:25 UTC, thlmenezes commented
Deployed pipeline for `PR #769 (docs: update webhook related instructions)`: Devopness application `thlmenezes-site.devopness.com` deployment **in-progress** on action <https://thlmenezes-site.devopness.com>

2023-10-16 13:26 UTC, thlmenezes commented
Deployed pipeline for `PR #769 (docs: update webhook related instructions)`: Devopness application `thlmenezes-site.devopness.com` deployment **completed** on action <https://thlmenezes-site.devopness.com>

2023-10-16 13:40 UTC, jfoliveira requested changes

2023-10-16 17:47 UTC, thlmenezes commented
Deployed pipeline for `PR #769 (docs: update webhook related instructions)`: Devopness application `thlmenezes-site.devopness.com` deployment **in-progress** on action <https://thlmenezes-site.devopness.com>

2023-10-16 17:49 UTC, thlmenezes commented
Deployed pipeline for `PR #769 (docs: update webhook related instructions)`: Devopness application `thlmenezes-site.devopness.com` deployment **completed** on action <https://thlmenezes-site.devopness.com>

2023-10-16 18:11 UTC, thlmenezes commented
Deployed pipeline for `PR #769 (docs: update webhook related instructions)`: Devopness application `thlmenezes-site.devopness.com` deployment **in-progress** on action <https://thlmenezes-site.devopness.com>

2023-10-16 18:13 UTC, thlmenezes commented
Deployed pipeline for `PR #769 (docs: update webhook related instructions)`: Devopness application `thlmenezes-site.devopness.com` deployment **completed** on action <https://thlmenezes-site.devopness.com>

2023-10-17 12:00 UTC, thlmenezes commented on docs/applications/deploy-application-using-incoming-hook.md
> +Once you have your `Deploy Pipeline ID` (`<pipeline_id>`), please follow the instructions below to add an incoming webhook to your application that triggers the deploy pipeline:
```suggestion
Once you have your `<pipeline_id>`, please follow the instructions below to add an incoming webhook to your application that triggers the deploy pipeline:
```

2023-10-17 12:02 UTC, thlmenezes commented on docs/applications/integrate-application-deployments-to-ci-workflows.md
> +1. Take note of the `Deploy Pipeline ID` (`<pipeline_id>`) from the application which you want to watch the action statuses
```suggestion
1. Take note of the `<pipeline_id>` from the application which you want to watch the action statuses
```

2023-10-17 12:07 UTC, thlmenezes commented on docs/webhooks/create-incoming-webhook.md
> +1. Copy the `Deploy Pipeline ID` (`<pipeline_id>`) from the application which you want to run pipelines programatically
```suggestion
1. Take note of the ID (`<pipeline_id>`) of a pipeline that runs the `deploy` operation for the application which you want to run pipelines programatically
```

2023-10-17 12:10 UTC, thlmenezes commented on docs/webhooks/create-outgoing-webhook.md
> +1. Take note of the `Deploy Pipeline ID` (`<pipeline_id>`) from the application which you want to watch the action statuses
```suggestion
1. Take note of the ID (`<pipeline_id>`) of a pipeline that runs the `deploy` operation for the application which you want to watch the action statuses
```

2023-10-17 12:23 UTC, jfoliveira requested changes

2023-10-17 12:23 UTC, jfoliveira commented on docs/applications/integrate-application-deployments-to-ci-workflows.md
> +1. On your local machine, in a terminal window, submit a request to Devopness API endpoint `POST /pipelines/:id/hooks/outgoing` to create a outgoing for the `action.started` event, replacing `<pipeli
```suggestion
1. On your local machine, in a terminal window, submit a request to Devopness API endpoint `POST /pipelines/:id/hooks/outgoing` to create an outgoing webhook for the `action.started` event. In the example below, replace `<pipeline_id>`, `<target_url>`, `<request_headers>` and `<request_body>` with the actual values of each parameter before submitting the request.
```

2023-10-17 12:23 UTC, jfoliveira commented on docs/applications/integrate-application-deployments-to-ci-workflows.md
> +1. On your local machine, in a terminal window, submit a request to Devopness API endpoint `POST /pipelines/:id/hooks/outgoing` to create a outgoing for the `action.failed` event, replacing `<pipelin
```suggestion
1. On your local machine, in a terminal window, submit a request to Devopness API endpoint `POST /pipelines/:id/hooks/outgoing` to create an outgoing webhook for the `action.failed` event. In the example below, replace `<pipeline_id>`, `<target_url>`, `<request_headers>` and `<request_body>` with the actual values of each parameter before submitting the request.
```

2023-10-17 12:23 UTC, jfoliveira commented on docs/applications/integrate-application-deployments-to-ci-workflows.md
> +1. On your local machine, in a terminal window, submit a request to Devopness API endpoint `POST /pipelines/:id/hooks/outgoing` to create a outgoing for the `action.completed` event, replacing `<pipe
```suggestion
1. On your local machine, in a terminal window, submit a request to Devopness API endpoint `POST /pipelines/:id/hooks/outgoing` to create an outgoing webhook for the `action.completed` event. In the example below, replace `<pipeline_id>`, `<target_url>`, `<request_headers>` and `<request_body>` with the actual values of each parameter before submitting the request.
```

2023-10-17 12:23 UTC, jfoliveira commented on docs/webhooks/create-outgoing-webhook.md
> +1. On your local machine, in a terminal window, submit a request to Devopness API endpoint `POST /pipelines/:id/hooks/outgoing` to create a outgoing webhook to comment on the Pull Request using the s
```suggestion
1. On your local machine, in a terminal window, submit a request to Devopness API endpoint `POST /pipelines/:id/hooks/outgoing` to create an outgoing webhook to comment on the Pull Request using the source provider where the application' source code is hosted. In the example below, replace `<pipeline_id>`, `<target_url>`, `<request_headers>` and `<request_body>` with the actual values of each parameter before submitting the request.
```

2023-10-17 12:23 UTC, jfoliveira commented on docs/applications/integrate-application-deployments-to-ci-workflows.md
> +1. On your local machine, in a terminal window, run command to list all the application hooks, replacing `<pipeline_id>`.
```suggestion
1. On your local machine, in a terminal window, run command to list all the pipeline webhooks, replacing `<pipeline_id>`.
```

2023-10-17 12:23 UTC, jfoliveira commented on docs/webhooks/create-incoming-webhook.md
> +1. On your local machine, in a terminal window, run command to list all the application hooks, replacing `<pipeline_id>`.
```suggestion
1. On your local machine, in a terminal window, run command to list all the pipeline webhooks, replacing `<pipeline_id>`.
```

2023-10-17 12:23 UTC, jfoliveira commented on docs/webhooks/create-outgoing-webhook.md
> +1. On your local machine, in a terminal window, run command to list all the application hooks, replacing `<pipeline_id>`.
```suggestion
1. On your local machine, in a terminal window, run command to list all the pipeline webhooks, replacing `<pipeline_id>`.
```

2023-10-17 12:47 UTC, jfoliveira approved these changes

2023-10-17 12:48 UTC, merged

2023-10-17 13:13 UTC, thlmenezes commented
Deployed pipeline for `PR #769 (docs: update webhook related instructions)`: Devopness application `thlmenezes-site.devopness.com` deployment **in-progress** on action <https://thlmenezes-site.devopness.com>