docs: add info about billing and credits
devopness/devopness pull request #779
Opened 2023-10-24 21:36 UTC by jfoliveira

## Description of change
Add docs about billing, billing settings, credits and usage limits.

## Issues resolved by this PR

- [x] [DVN-12215]

## More info

## Why draft?
- [ ] Format text and mentioned links

2023-10-24 22:23 UTC, thlmenezes requested changes

2023-10-24 22:23 UTC, thlmenezes commented on docs/users/subscriptions/index.md
> +These limits are subject to change every time our plans are updated. For details, see our pricing page https://www.devopness.com/pricing/
The domain can be removed using markdown links

```suggestion
These limits are subject to change every time our plans are updated. For details, see our [pricing page](/pricing)
```

this pattern is also applied here
 https://github.com/devopness/devopness/blob/bc0246e755845541a04b269d73e2f225e03dd0f3/docs/users/subscriptions/faq/index.md?plain=1#L22

2023-10-24 22:23 UTC, thlmenezes commented on docs/users/subscriptions/index.md
> +In addition to the usage limits, you must ensure that you use Devopness within our {% mentionPost "/docs/legal/terms-of-service/" %}
The current implementation of `mentionPost` does not handle paths terminated with '/', causing a build error

```suggestion
In addition to the usage limits, you must ensure that you use Devopness within our {% mentionPost "/docs/legal/terms-of-service" %}
```

2023-10-24 23:19 UTC, plantaz approved these changes

2023-10-25 01:44 UTC, thlmenezes approved these changes

2023-10-25 10:31 UTC, merged