feat: create help needed issue form
devopness/devopness pull request #821
Opened 2023-12-11 03:49 UTC by thlmenezes

## Description of change

## Issues resolved by this PR

- [ ] [DVN-<task or subtask number here>]

## More info

2023-12-12 19:59 UTC, brlipi approved these changes

2023-12-12 23:32 UTC, jfoliveira requested changes

2023-12-12 23:32 UTC, jfoliveira commented on .github/ISSUE_TEMPLATE/help_needed.yml
> +    description: "Describe what you are struggling with"
```suggestion
    description: "Describe what you are trying to accomplish and the issues you encountered"
```

2023-12-13 15:53 UTC, jfoliveira commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Please ask and answer questions here
```suggestion
  - name: 💬 Questions & Discussions
    url: https://github.com/orgs/devopness/discussions
    about: Ask questions and discuss ideas and best practices with other Devopness community members
```

2023-12-13 22:16 UTC, jfoliveira approved these changes

2023-12-14 00:40 UTC, merged