docs: fix articles archive/unarchive an environment (#884)
devopness/devopness pull request #894
Opened 2024-03-04 18:32 UTC by oliverigor27

## Description of changes

This commit addresses the "Archive/Unarchive an Environment" issue by updating the documentation.

- [x]  Update "Select a project" step
- [x]  Remove "Find the Environments card" step, removing duplicated step
- [x]  Guide the user to click SETTINGS

## GitHub issues resolved by this PR

- [ ] closes #884

## Quality Assurance

- Once the changes in this PR are merged and deployed, success criteria is: 
- Add clear instructions for the users who wants to archiving/unarchiving environments.

2024-03-04 18:43 UTC, thlmenezes requested changes
Thank you for contributing @oliverigor27

Left some suggestions below to improve the article with your help

2024-03-04 19:44 UTC, oliverigor27 commented on docs/environments/unarchive-environment.md
> +1. On the upper-right corner of the `Environment` resources list, click **SETTINGS**
Ok, i'm gonna do that

2024-03-04 20:34 UTC, oliverigor27 commented on docs/environments/archive-environment.md
>  1. Use the drop-down menu to choose `Archive`
Done!

2024-03-04 20:34 UTC, oliverigor27 commented on docs/environments/unarchive-environment.md
>  1. Use the drop-down menu to choose `Unarchive`
Done!

2024-03-04 20:34 UTC, oliverigor27 commented on docs/environments/archive-environment.md
> +1. On the upper-right corner of the `Environment` resources list, click **SETTINGS**
Done!

2024-03-04 21:49 UTC, thlmenezes approved these changes

2024-03-05 14:34 UTC, jfoliveira commented
@cla-bot check

2024-03-05 14:34 UTC, jfoliveira approved these changes

2024-03-05 14:34 UTC, merged