docs: fix article "Stop a Server" to guide the user to click resource name
devopness/devopness pull request #937
Opened 2024-03-31 15:03 UTC by dudunog

## Description of changes

- [ ] Fixed the excerpts "In the list of servers, find the server you want to restart and click DETAILS" that was replaced by a more descriptive text explaining how to enter in the server details view.
- [ ] Updated public IP address to warning

## GitHub issues resolved by this PR

- [ ] This PR resolves #877

## Quality Assurance

- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/servers/stop-server/

## More info

2024-03-31 16:47 UTC, thlmenezes submitted a review, later dismissed

2024-04-02 16:04 UTC, jfoliveira requested changes

2024-04-02 16:04 UTC, jfoliveira commented on docs/servers/stop-server.md
> +**WARNING**: Your server's public IP address will be updated the next time the server is started, unless you have configured an elastic IP on your cloud provider management panel; meaning, the next t
```suggestion
**WARNING**: Your server's public IP address will be updated the next time the server is started, unless you have a static IP address set configured for the selected instance on your cloud provider. That means that if your server does not have a static IP address associated to it, the next time this server is started all domains that point to this server's old IP address will need to be updated to point to the server's new IP address.
```

2024-04-07 13:35 UTC, dudunog commented on docs/servers/stop-server.md
> +**WARNING**: Your server's public IP address will be updated the next time the server is started, unless you have configured an elastic IP on your cloud provider management panel; meaning, the next t
Resolved!

2024-04-07 20:22 UTC, thlmenezes approved these changes

2024-04-08 20:36 UTC, jfoliveira approved these changes

2024-04-08 20:37 UTC, merged