docs: fix article "Deploy Application using an Incoming Hook" to guide the user to click resource name and to use the tabs
devopness/devopness pull request #941
Opened 2024-03-31 16:48 UTC by dudunog

## Description of changes

- [ ] Fixed the excerpt "In the list of applications, find the application with the pipeline you want to manage and click DETAILS", 'In the list of pipelines, find the pipeline you want to manage and click DETAILS' and 'Click DETAILS on the application you triggered the pipeline' that were replaced by a more descriptive text explaining how to enter in the file details view.
- [ ] Guided the user to use Tabs
- [ ] Updated text to show <pipeline_id> as text

## GitHub issues resolved by this PR

- [ ] This PR resolves #859 

## Quality Assurance

- Once the changes in this PR are merged and deployed, success criteria is: Update the article https://www.devopness.com/docs/applications/deploy-application-using-incoming-hook/

## More info

2024-03-31 18:09 UTC, thlmenezes requested changes

2024-03-31 18:09 UTC, thlmenezes commented on docs/applications/deploy-application-using-incoming-hook.md
Nothing was changed to address the issue below, listed in #859 

>  - Update text to show <pipeline_id> as text
>        - ❌ Steps to find the `` of an application:deploy pipeline
>        - ✅ Steps to find the pipeline_id of an application:deploy pipeline

The following diff solves the issue

```diff
-   <summary>Steps to find the `<pipeline_id>` of an `application:deploy` pipeline</summary>
+   <summary>Steps to find the <code>&lt;pipeline_id&gt;</code> of an <code>application:deploy</code> pipeline</summary>
```

2024-03-31 18:58 UTC, dudunog commented on docs/applications/deploy-application-using-incoming-hook.md
Fixed!

2024-04-01 01:42 UTC, thlmenezes approved these changes

2024-04-02 15:55 UTC, jfoliveira approved these changes

2024-04-02 15:56 UTC, merged