feat: 2024-05-13 18:46 - Update API specification
devopness/devopness pull request #955
Opened 2024-05-13 18:46 UTC by devopness-automations

This PR is auto generated to update `spec.json` file.

2024-05-14 00:14 UTC, Diegiwg approved these changes

2024-05-14 01:04 UTC, souz4-my requested changes

2024-05-14 01:04 UTC, souz4-my commented on packages/sdks/javascript/src/api/generated/models/virtual-host-relation.ts
> +    application_listen_address: string;
Campo deveria ser do tipo  "string | null" semelhante ao "last_action" abaixo, pois usuário pode querer remover o campo ao editar e nem todas aplicação terá esse campo preenchido ao criar

2024-05-14 01:13 UTC, Diegiwg commented on packages/sdks/javascript/src/api/generated/models/virtual-host-relation.ts
> +    application_listen_address: string;
O campo já está marcado como "sometimes|nullable" nas requests. Atualizei no resource/collection e estou fazendo o build. Volto com noticias em alguns minutos.

2024-05-14 01:50 UTC, thlmenezes commented on packages/sdks/javascript/src/api/generated/models/virtual-host-relation.ts
> +    application_listen_address: string;
@souz4-my VirtualHostRelation vai ser o retorno do GET INDEX, então acredito que nesse caso ambos root_directory e application_listen_address precisariam ser no formato abaixo

```suggestion
    application_listen_address?: string;
```

É separado do problema descrito por ti, que pode ser encontrado em https://github.com/devopness/devopness/pull/955/files#diff-e6b8a9f9c59ebec763393ef7b81b0fa900207bd6ce46cf5b76efd3da0b981250R45

2024-05-14 23:32 UTC, Diegiwg commented on packages/sdks/javascript/src/api/generated/models/virtual-host-relation.ts
> +    application_listen_address: string;
@thlmenezes qual a diferença entre `field: string|null` e `field?: string`?

2024-05-14 23:41 UTC, Diegiwg commented on packages/sdks/javascript/src/api/generated/models/virtual-host-relation.ts
> +    application_listen_address: string;
Um GET em um Virtual Host sem vinculo com Application, devolve os campos `"application" => null` e `"application_listen_address" => null`.

Pelo que entendi pesquisando, a notação `field?: string` significa que o field `pode ou não existir`, e caso exista, ele tem o tipo string.

Neste caso, como sempre temos o field `application_listen_address`, acredito que o correto seja mesmo `string|null`.

![image](https://github.com/devopness/devopness/assets/15692310/1e6d64dd-6d1f-49b7-a5fc-aaabee95d68d)
![image](https://github.com/devopness/devopness/assets/15692310/c6954753-46d6-49f4-83d5-f6862460c593)

2024-05-14 23:50 UTC, thlmenezes requested changes

2024-05-14 23:50 UTC, thlmenezes commented on packages/sdks/javascript/src/api/generated/models/virtual-host-relation.ts
>      root_directory: string;
@Diegiwg shouldn't this field include null? I believe a virtual host is not required to have a `root_directory`

```suggestion
    root_directory: string | null;
```

2024-05-14 23:50 UTC, thlmenezes commented on packages/sdks/javascript/src/api/generated/models/virtual-host-update.ts
> +    application_id?: number;
@Diegiwg shouldn't this field include null? When a user wants to remove a link between Virtual Host and Application the value sent to the API is null

```suggestion
    application_id?: number | null;
```

2024-05-14 23:50 UTC, thlmenezes commented on packages/sdks/javascript/src/api/generated/models/virtual-host.ts
>      root_directory: string;
Same question as commented at [packages/sdks/javascript/src/api/generated/models/virtual-host-relation.ts](https://github.com/devopness/devopness/pull/955/files/bdd720bc1b986323abc89ab7013718891ee6ee43#diff-88bf862d3c5443a4c3b8ab24cd30a1cd3d3acf4f59c28f74f2da9de2b9e92ded)

2024-05-14 23:50 UTC, thlmenezes commented on packages/sdks/javascript/src/api/generated/models/virtual-host-relation.ts
> +    application_listen_address: string;
> pode ou não existir, e caso exista, ele tem o tipo string

"pode ou não existir" == undefined
"pode ou não existir" != null

```ts
function formatFieldRequired(field: string | null){}

formatFieldRequired()
// error => An argument for 'field' was not provided
formatFieldRequired(undefined)
// error => Argument of type 'undefined' is not assignable to parameter of type 'string | null'
formatFieldRequired('') // ok
formatFieldRequired(null) // ok

function formatFieldNotRequired(field?: string){}

formatFieldNotRequired() // ok
formatFieldNotRequired(undefined) // ok
formatFieldNotRequired('') // ok
formatFieldNotRequired(null)
// error => Argument of type 'null' is not assignable to parameter of type 'string | undefined'

function formatFieldNotRequired2(field: string | undefined){}

formatFieldNotRequired2()
// error => An argument for 'field' was not provided
formatFieldNotRequired2(undefined) // ok
formatFieldNotRequired2('') // ok
formatFieldNotRequired2(null)
// error => Argument of type 'null' is not assignable to parameter of type 'string | undefined'
```

[TS Playground](https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABMOAnAtgQygMRgUwBsATAJXwEcQZV9iAKYAkgLkQGcpUYwBzRAD6IwIQoQCUAbwC+AKFkoM2PETKVqtBuNkB6HYnypUaRAF4AfIgCCSTKl4h0+MFGQmA5E1XvEAd0zswnCuAA7GAG4wxHQKaFi4zGpUNHT04NFMYHTaegZGJhbW9o7OrnDAiFAAniH4iO7p+Jl0PjCBYMGIAewwvGCYAEaEdVBwiCF2mE5QhojllTV17pzcfILCooTusUoJquTJmvTu7uKIuXAA1jvxKiQHGqkiYmcX1wrg0PBIireJAHLBB4pBheEgAfjYKx4vCkchuygBQPUIPor30VwRexIgKgwKOjWaxHRc2uv0Rqlx+NSJxJmPJ2OIVJRR2eEl0+kMxlQZksVmKThccwq1Vq9TZrXanW6vX6QxGYwmqCm+BmPPmoqW0LWQkJPBa8lAkFgCDcuzuTORhzoACZGIkoVwYes9VliTJDXEKTirY9iHacpz8jzCjYugLSmb6mDiD5-FLQhEojEGRbmdb-WkwBl9cTzhiyV7Gem-XbafnSVi076QXa2YG8tzeUUHIKyiLFuLNpKgq4ZX1BsNKorJtNZhrO8snTrEK6WkA)

2024-05-14 23:50 UTC, thlmenezes commented on packages/sdks/javascript/src/api/generated/models/virtual-host-relation.ts
> +    application_listen_address: string;
De toda forma, abri threads separadas pq aqui estamos discutindo mais de um tópico ao mesmo tempo

2024-05-14 23:54 UTC, thlmenezes commented on packages/sdks/javascript/src/api/generated/models/virtual-host-relation.ts
>      root_directory: string;
As seen in VirtualHostCreate and VirtualHostUpdate

https://github.com/devopness/devopness/blob/bdd720bc1b986323abc89ab7013718891ee6ee43/packages/sdks/javascript/src/api/generated/models/virtual-host-environment-create.ts#L39

https://github.com/devopness/devopness/blob/bdd720bc1b986323abc89ab7013718891ee6ee43/packages/sdks/javascript/src/api/generated/models/virtual-host-update.ts#L39

2024-05-14 23:57 UTC, thlmenezes commented on packages/sdks/javascript/src/api/generated/models/virtual-host-update.ts
> +    application_id?: number;
Example of PUT /virtual-host/123, that I want to remove the application link

```json
{
  "id": 123
  "type": "name-based",
  "name": "my-site.example.com",
  "root_directory": "public",
  "forward_server_address": "http://localhost:3000",
  "application_id": null
}
```

2024-05-16 12:52 UTC, thlmenezes approved these changes
LGTM

2024-05-16 13:02 UTC, Diegiwg approved these changes

2024-05-16 13:14 UTC, thlmenezes approved these changes

2024-05-16 13:30 UTC, merged